import Head from "next/head"
import { Box, Button, Flex, Heading, Select, Text } from "@chakra-ui/react"
import axios from "axios"
import Link from "next/link"
import NavBar from "@/components/NavBar"

export default function Home({ facts }: { facts: Record<string, any>[] }) {
  return (
    <>
      <Head>
        <title>LGBTQuery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar isHomepage={true} />
      <Flex flexDir="column" height="100vh" justify="center" align="center">

        <Flex m="8px" border={"1px solid black"} borderRadius={"8px"} width={"40%"} height={"40%"} padding="32px" align="center" flexDir="column">
          <Heading size={"md"}>Hi there! Fill in your data</Heading>
          <Box margin={"32px"}>
            <Flex mt={"8px"}>
              <Text minWidth="128px">Project Type:</Text>
              <Select minWidth="256px">
                <option value="cool">Cool</option>
                <option value="neat">Neat</option>
              </Select>
            </Flex>
            <Flex mt={"8px"}>
              <Text minWidth="128px">Language:</Text>
              <Select minWidth="256px">
                <option value="Javascript">Javascript</option>
                <option value="Python">Python</option>
              </Select>
            </Flex>
          </Box>
          <Button>
            <Link href={"/results"}>Click here for the app</Link>
          </Button>
        </Flex>
      </Flex>
    </>
  )
}

export async function getStaticProps() {
  // test for getting props
  const { data } = await axios("https://cat-fact.herokuapp.com/facts")

  return {
    props: {
      facts: data,
    },
  }
}