import Head from "next/head"
import { Box, Button, Flex, Heading } from "@chakra-ui/react"
import axios from "axios"
import Link from "next/link"

export default function Home({ facts }: { facts: Record<string, any>[] }) {
  return (
    <>
      <Head>
        <title>Lovelace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDir="column" height="100vh" justify="center" align="center">
        <Heading>Hello world</Heading>
        <Flex m="8px" align="center" flexDir="column">
          {facts.map((fact) => (
            <Box key={fact.text} mt="4px">
              {fact.text}
            </Box>
          ))}
        </Flex>
        <Button>
          <Link href={"/test"}>Click here for the app</Link>
        </Button>
      </Flex>
    </>
  )
}

export async function getStaticProps() {
  // test for getting props
  const { data } = await axios("https://cat-fact.herokuapp.com/facts")

  return {
    props: {
      facts: data,
    },
  }
}